name: tags
'on':
  push:
    tags:
      - "v*"
    
jobs:
  asd:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello"